client/components/auth-form.js, client/components/navbar.js, package-lock.json, package.json, public/index.html
---
Added stylesheets to index.html, npm install of material-ui
=> added material-ui styling, icons, and button

server/db/models/user.js
=> User model #21

server/db/models/mask.js
=> Mask model

server/db/models/order.js
=> models for Order

server/db/models/order.js
---
Added all of our mask products into the seed value
=> Seed the Database with all the Masks

server/db/models/index.js, server/db/models/mask.spec.js
=> create mask model tests

server/db/models/cart.js
=> Cart model #16

server/db/models/index.js, server/db/models/mask.spec.js
---
I originally pushed the mask model test spec up and it was approved and merged, yet when I pull from master it is nowhere to be found so I re-added and recommitted
=> re-add mask model test spec

package-lock.json, script/seed.js
---
Updated the seed file so that the masks weren't being bulk created (changed from bulkCreate to Mask.create due to errors while seeding the db)
=> Update seed mask

script/seed.js
---
Found a shorter Url so that character is less than 255
=> Shortened the Joker imgineUrl

server/api/index.js, server/api/masks.js, server/api/masks.spec.js
---
added the get all masks route along with test specs
=> add get all masks route and tests

server/db/models/cart.js
Add associations for models (please, need to be confirmed all team members)
---
=> add associations

client/components/all-masks.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/mask.js
=> feat: render all masks

client/components/all-masks.js, client/components/index.js, client/components/single-mask.js, client/routes.js, client/store/index.js, client/store/mask.js, client/store/singleMask.js, server/api/masks.js
---
Set up the React component for Single Mask view, along with the thunk and the reducer. 
*ALERT: THE SINGLE MASK VIEW DOES NOT WORK AS OF NOW*
=> Setting up the Mask Single View

server/db/models/index.js
---
Resubmitted the associations cause I need them for the cart-page.
=> added model associations

client/routes.js
=> fix react routes for loading components

client/routes.js
=> updated singleMask route

client/routes.js
=> switch order of routes

script/seed.js
---
Add more users to work with in the seed file, also added connections of some cart products to those users
=> Updated the user dummy data

client/components/navbar.js, client/routes.js, client/store/user.js
=> fixed issues with component mounting and navigation in navbar

client/components/cart-page.js, client/routes.js, client/store/cart.js, server/api/cart.js, server/api/index.js, server/db/models/order.js
=> Cart routers

client/routes.js
=> fixed the darn routing issues

client/components/all-masks.js
---
Whoops, forgot to fix Link in allMasks at the same time...
=> fixed Link in all masks component to match component routing

.travis.yml
---
Updated the deployment functionality so that our whenever master is updated on GitHub, Travis will automatically push the app to Heroku.
=> Update the deployment functionality

.travis.yml
---
Updating the database and potential solution for a bug for Travis CI
=> Updates for Heroku/Travis CI

client/store/user.spec.js, script/seed.js, server/api/masks.spec.js, server/db/models/mask.spec.js
---
I mades some edits to the test specs so that they could all pass. I believe for travis to work, all tests need to be passing so hopefully it will work now.
=> Updating the test specs to get the tests all passing for Travis

client/components/cart-item.js, client/components/cart-page.js
=> refactored cartPage to use new CartItem component

client/components/cart-item.js, client/components/cart-page.js, client/store/cart.js, server/api/cart.js
=> update cart route, store, component

client/components/cart-item.js, client/components/cart-page.js, client/store/cart.js, server/api/cart.js
=> fix update cart feature: component, store, and api route

client/store/cart.js, server/api/cart.js
=> Save price order submit

client/components/single-mask.js, client/components/thanks.js, client/store/cart.js, server/api/cart.js, server/auth/index.js
=> Create new order after checkout

server/auth/index.js
=> add new order during user signup

client/components/checkout.js
=> update: add form to checkout page

client/components/checkout.js
=> Update checkout form

client/components/all-masks-list-item.js, client/components/all-masks.js, public/style.css
=> update allMask view with grid

server/api/admin.js, server/api/index.js
---
Added routers for admin to protect data
=> Admin routes

server/api/cart.js
---
add middleware isLogging to protect user data in cart
=> add middleware to protect user data in cart

server/api/cart.js
Reverts Team-One-Grace-Shopper/GraceShopper#97
View cart feature was working, but update cart feature was blocked with new update.
=> Revert "add middleware to protect user data in cart"

client/components/cart-item.js, client/components/cart-page.js, client/store/cart.js, server/api/cart.js
=> update api updateCart route for protection

client/components/cart-item.js, client/components/cart-page.js, client/store/cart.js, server/api/cart.js
=> fix deleteItem component, store, and API route

client/store/cart.js
=> Update total feat
